Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

In [2]:
import numpy as np

In [3]:
def orderpower(i,j):
    x = np.array(i)
    N = j
    return (np.column_stack([x**(N-1-i) for i in range(N)]))

i=[1,2,3,5]
j=3
res=orderpower(i,j)
print(res)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
